Mission 2 - Exploring and Analyzing Data with Pandas
Objective:

In this mission, you will perform Exploratory Data Analysis (EDA) and basic data manipulation using Pandas. You will work with a dataset that includes information about employees and apply various data transformation techniques, including handling missing values, filtering, and performing basic data analysis.

Dataset Overview:

The dataset contains the following columns:

employee_id: Unique identifier for each employee.

name: Name of the employee.

age: Age of the employee.

department: The department where the employee works (e.g., HR, Engineering, Marketing).

salary: Annual salary of the employee.

work_experience: Number of years of work experience the employee has.

Task 1: Load the Data
Objective: Load the dataset into a Pandas DataFrame.

Instructions:

Create a DataFrame from the provided dataset.

Display the first few rows of the dataset to ensure it loaded correctly.

In [1]:
import pandas as pd

In [2]:
# create a basic provided dataset
data = {
    'employee_id': range(1, 21),
    'name': ['John', 'Jane', 'Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack', 'Karen', 'Leo', 'Mia', 'Nina', 'Olivia', 'Paul', 'Quinn', 'Rita'],
    'age': [22, 25, 28, 35, 40, 42, 50, 60, 65, 30, 28, 24, 37, 41, 48, 33, 29, 32, 45, 38],
    'department': ['HR', 'Engineering', 'Marketing', 'Finance', 'Sales', 'HR', 'Engineering', 'Marketing', 'Finance', 'Sales', 'HR', 'Engineering', 'Marketing', 'Finance', 'Sales', 'HR', 'Engineering', 'Marketing', 'Finance', 'Sales'],
    'salary': [50000, 60000, 55000, 75000, 80000, 85000, 100000, 110000, 120000, 65000, 67000, 72000, 85000, 90000, 95000, 48000, 67000, 70000, 80000, 88000],
    'work_experience': [1, 3, 5, 7, 10, 12, 15, 18, 20, 3, 1, 6, 4, 8, 5, 7, 3, 2, 6, 5],
}

In [4]:
# Takes the raw data and turns it into a neat table with rows and columns called a DataFrame(saved as df)
df = pd.DataFrame(data)

# Displays the table
display(df)

    employee_id     name  age   department  salary  work_experience
0             1     John   22           HR   50000                1
1             2     Jane   25  Engineering   60000                3
2             3    Alice   28    Marketing   55000                5
3             4      Bob   35      Finance   75000                7
4             5  Charlie   40        Sales   80000               10
5             6    David   42           HR   85000               12
6             7      Eve   50  Engineering  100000               15
7             8    Frank   60    Marketing  110000               18
8             9    Grace   65      Finance  120000               20
9            10   Hannah   30        Sales   65000                3
10           11      Ivy   28           HR   67000                1
11           12     Jack   24  Engineering   72000                6
12           13    Karen   37    Marketing   85000                4
13           14      Leo   41      Finance   90000                8
14           15      Mia   48        Sales   95000                5
15           16     Nina   33           HR   48000                7
16           17   Olivia   29  Engineering   67000                3
17           18     Paul   32    Marketing   70000                2
18           19    Quinn   45      Finance   80000                6
19           20     Rita   38        Sales   88000                5

Task 1: Load the Data
Objective: Load the dataset into a Pandas DataFrame.

Instructions:

Create a DataFrame from the provided dataset.

Display the first few rows of the dataset to ensure it loaded correctly.

In [5]:
##Code here

# Checks every cell on the DataFrame and creates a new table of True and False values showing where data is missing.
missing_values = df.isnull()

# As shown on the table, there are no missing values as it returns all cells are false
display(missing_values)

    employee_id   name    age  department  salary  work_experience
0         False  False  False       False   False            False
1         False  False  False       False   False            False
2         False  False  False       False   False            False
3         False  False  False       False   False            False
4         False  False  False       False   False            False
5         False  False  False       False   False            False
6         False  False  False       False   False            False
7         False  False  False       False   False            False
8         False  False  False       False   False            False
9         False  False  False       False   False            False
10        False  False  False       False   False            False
11        False  False  False       False   False            False
12        False  False  False       False   False            False
13        False  False  False       False   False            False
14        False  False  False       False   False            False
15        False  False  False       False   False            False
16        False  False  False       False   False            False
17        False  False  False       False   False            False
18        False  False  False       False   False            False
19        False  False  False       False   False            False

In [7]:
# Another way to check for missing values, this filters your DataFrame to keep and display only the rows that have at least one missing value.
rows_with_nulls = df[missing_values.any(axis=1)]

display(rows_with_nulls)

Empty DataFrame
Columns: [employee_id, name, age, department, salary, work_experience]
Index: []

In [8]:
# Summary statistics of numeric columns (age, salary, work_experience)
numeric_summary = df[['age', 'salary', 'work_experience']].describe().round(2)

display(numeric_summary)
# count: the number of non-missing(non-null)values
# mean: the average value
# std: standard deviation-how spread out the numbers are around the mean
# min: the lowest value in the column
# 25%: the 1st quartile- 25% of values fall below this number
# 50%: the median(middle value)- half the data is above, half is below
# 75%: the 3rd quartile- 75% of values fall below this number
# max: the highest value in the column

         age    salary  work_experience
count  20.00      20.0            20.00
mean   37.60   78100.0             7.05
std    11.63   19150.1             5.41
min    22.00   48000.0             1.00
25%    28.75   66500.0             3.00
50%    36.00   77500.0             5.50
75%    42.75   88500.0             8.50
max    65.00  120000.0            20.00

Task 3: Data Transformation
Objective: Perform basic data transformations such as creating new columns and renaming existing ones.

Instructions:

Create a new column called years_to_retirement by subtracting the age from 65.

Rename the salary column to annual_salary.

Sort the DataFrame based on work_experience in descending order.

In [9]:
##Code here

# Adding a new column called years_to_retirement that calculates how many years each person has left until they reach the retirement age of 65
df['years_to_retirement'] = 65 - df['age']

display(df)

,employee_id,name,age,department,salary,work_experience,years_to_retirement
0,1,John,22,HR,50000,1,43
1,2,Jane,25,Engineering,60000,3,40
2,3,Alice,28,Marketing,55000,5,37
3,4,Bob,35,Finance,75000,7,30
4,5,Charlie,40,Sales,80000,10,25
5,6,David,42,HR,85000,12,23
6,7,Eve,50,Engineering,100000,15,15
7,8,Frank,60,Marketing,110000,18,5
8,9,Grace,65,Finance,120000,20,0
9,10,Hannah,30,Sales,65000,3,35
10,11,Ivy,28,HR,67000,1,37
11,12,Jack,24,Engineering,72000,6,41
12,13,Karen,37,Marketing,85000,4,28
13,14,Leo,41,Finance,90000,8,24
14,15,Mia,48,Sales,95000,5,17
15,16,Nina,33,HR,48000,7,32
16,17,Olivia,29,Engineering,67000,3,36
17,18,Paul,32,Marketing,70000,2,33
18,19,Quinn,45,Finance,80000,6,20
19,20,Rita,38,Sales,88000,5,27

In [10]:
# Renaming the salary column to annual_salary
df = df.rename(columns={'salary': 'annual_salary'})

display(df)

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
0,1,John,22,HR,50000,1,43
1,2,Jane,25,Engineering,60000,3,40
2,3,Alice,28,Marketing,55000,5,37
3,4,Bob,35,Finance,75000,7,30
4,5,Charlie,40,Sales,80000,10,25
5,6,David,42,HR,85000,12,23
6,7,Eve,50,Engineering,100000,15,15
7,8,Frank,60,Marketing,110000,18,5
8,9,Grace,65,Finance,120000,20,0
9,10,Hannah,30,Sales,65000,3,35
10,11,Ivy,28,HR,67000,1,37
11,12,Jack,24,Engineering,72000,6,41
12,13,Karen,37,Marketing,85000,4,28
13,14,Leo,41,Finance,90000,8,24
14,15,Mia,48,Sales,95000,5,17
15,16,Nina,33,HR,48000,7,32
16,17,Olivia,29,Engineering,67000,3,36
17,18,Paul,32,Marketing,70000,2,33
18,19,Quinn,45,Finance,80000,6,20
19,20,Rita,38,Sales,88000,5,27

In [11]:
# Sorting the DataFrame based on work_experience in descending order
df_sorted = df.sort_values(by='work_experience', ascending=False)

display(df_sorted)

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
8,9,Grace,65,Finance,120000,20,0
7,8,Frank,60,Marketing,110000,18,5
6,7,Eve,50,Engineering,100000,15,15
5,6,David,42,HR,85000,12,23
4,5,Charlie,40,Sales,80000,10,25
13,14,Leo,41,Finance,90000,8,24
15,16,Nina,33,HR,48000,7,32
3,4,Bob,35,Finance,75000,7,30
18,19,Quinn,45,Finance,80000,6,20
11,12,Jack,24,Engineering,72000,6,41
2,3,Alice,28,Marketing,55000,5,37
14,15,Mia,48,Sales,95000,5,17
19,20,Rita,38,Sales,88000,5,27
12,13,Karen,37,Marketing,85000,4,28
16,17,Olivia,29,Engineering,67000,3,36
1,2,Jane,25,Engineering,60000,3,40
9,10,Hannah,30,Sales,65000,3,35
17,18,Paul,32,Marketing,70000,2,33
0,1,John,22,HR,50000,1,43
10,11,Ivy,28,HR,67000,1,37

Task 4: Handling Missing Data
Objective: Handle missing data (if any).

Instructions:

Introduce some missing values in the annual_salary column.

Handle the missing data by either filling it with the mean salary or dropping the rows with missing values.

In [12]:
##Code here

# How to introduce some missing values in the annual_salary column.

# Numpy provides np.nan, which is the tool used to create missing values in Pandas.
import numpy as np

# Set rows 1 and 4 of 'annual_salary' to missing (Nan)
df.loc[[1, 4], 'annual_salary'] = np.nan

display(df)

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
0,1,John,22,HR,50000.0,1,43
1,2,Jane,25,Engineering,NaN,3,40
2,3,Alice,28,Marketing,55000.0,5,37
3,4,Bob,35,Finance,75000.0,7,30
4,5,Charlie,40,Sales,NaN,10,25
5,6,David,42,HR,85000.0,12,23
6,7,Eve,50,Engineering,100000.0,15,15
7,8,Frank,60,Marketing,110000.0,18,5
8,9,Grace,65,Finance,120000.0,20,0
9,10,Hannah,30,Sales,65000.0,3,35
10,11,Ivy,28,HR,67000.0,1,37
11,12,Jack,24,Engineering,72000.0,6,41
12,13,Karen,37,Marketing,85000.0,4,28
13,14,Leo,41,Finance,90000.0,8,24
14,15,Mia,48,Sales,95000.0,5,17
15,16,Nina,33,HR,48000.0,7,32
16,17,Olivia,29,Engineering,67000.0,3,36
17,18,Paul,32,Marketing,70000.0,2,33
18,19,Quinn,45,Finance,80000.0,6,20
19,20,Rita,38,Sales,88000.0,5,27

In [13]:
# Calculate average (mean) salary of the existing data (pandas automatically ignores Null/NaNs when calculating mean)
mean_salary = df['annual_salary'].mean()

# Fill Null/NaNs with the mean (average value)
df['annual_salary'] = df['annual_salary'].fillna(mean_salary)

display(df)

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
0,1,John,22,HR,50000.0,1,43
1,2,Jane,25,Engineering,79000.0,3,40
2,3,Alice,28,Marketing,55000.0,5,37
3,4,Bob,35,Finance,75000.0,7,30
4,5,Charlie,40,Sales,79000.0,10,25
5,6,David,42,HR,85000.0,12,23
6,7,Eve,50,Engineering,100000.0,15,15
7,8,Frank,60,Marketing,110000.0,18,5
8,9,Grace,65,Finance,120000.0,20,0
9,10,Hannah,30,Sales,65000.0,3,35
10,11,Ivy,28,HR,67000.0,1,37
11,12,Jack,24,Engineering,72000.0,6,41
12,13,Karen,37,Marketing,85000.0,4,28
13,14,Leo,41,Finance,90000.0,8,24
14,15,Mia,48,Sales,95000.0,5,17
15,16,Nina,33,HR,48000.0,7,32
16,17,Olivia,29,Engineering,67000.0,3,36
17,18,Paul,32,Marketing,70000.0,2,33
18,19,Quinn,45,Finance,80000.0,6,20
19,20,Rita,38,Sales,88000.0,5,27

In [14]:
# Dropping the rows with missing data

# First, let's create missing values based on a different category, specifically for employees under 25 years old.
df.loc[df['age'] < 25, 'annual_salary'] = np.nan

# Under 25 of age are employee_id=1 John (HR) and employee_id=2 Jack (Engineering)
display(df)

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
0,1,John,22,HR,NaN,1,43
1,2,Jane,25,Engineering,79000.0,3,40
2,3,Alice,28,Marketing,55000.0,5,37
3,4,Bob,35,Finance,75000.0,7,30
4,5,Charlie,40,Sales,79000.0,10,25
5,6,David,42,HR,85000.0,12,23
6,7,Eve,50,Engineering,100000.0,15,15
7,8,Frank,60,Marketing,110000.0,18,5
8,9,Grace,65,Finance,120000.0,20,0
9,10,Hannah,30,Sales,65000.0,3,35
10,11,Ivy,28,HR,67000.0,1,37
11,12,Jack,24,Engineering,NaN,6,41
12,13,Karen,37,Marketing,85000.0,4,28
13,14,Leo,41,Finance,90000.0,8,24
14,15,Mia,48,Sales,95000.0,5,17
15,16,Nina,33,HR,48000.0,7,32
16,17,Olivia,29,Engineering,67000.0,3,36
17,18,Paul,32,Marketing,70000.0,2,33
18,19,Quinn,45,Finance,80000.0,6,20
19,20,Rita,38,Sales,88000.0,5,27

In [15]:
# Drop only the rows where 'annual_salary' is Null/NaN
df = df.dropna(subset=['annual_salary'])

# John and Jack's row was dropped
display(df)

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
1,2,Jane,25,Engineering,79000.0,3,40
2,3,Alice,28,Marketing,55000.0,5,37
3,4,Bob,35,Finance,75000.0,7,30
4,5,Charlie,40,Sales,79000.0,10,25
5,6,David,42,HR,85000.0,12,23
6,7,Eve,50,Engineering,100000.0,15,15
7,8,Frank,60,Marketing,110000.0,18,5
8,9,Grace,65,Finance,120000.0,20,0
9,10,Hannah,30,Sales,65000.0,3,35
10,11,Ivy,28,HR,67000.0,1,37
12,13,Karen,37,Marketing,85000.0,4,28
13,14,Leo,41,Finance,90000.0,8,24
14,15,Mia,48,Sales,95000.0,5,17
15,16,Nina,33,HR,48000.0,7,32
16,17,Olivia,29,Engineering,67000.0,3,36
17,18,Paul,32,Marketing,70000.0,2,33
18,19,Quinn,45,Finance,80000.0,6,20
19,20,Rita,38,Sales,88000.0,5,27

Task 5: Data Filtering and Selection
Objective: Select specific data based on conditions.

Instructions:

Filter the data to show only employees who are older than 30.

Select only the columns name, age, and annual_salary.

In [16]:
##  Code here

# This filters the DataFrame to keep only emplyees who are age over 30 and we ascend them into order.
over_30 = df[df['age'] > 30].sort_values(by='age', ascending=True)

display(over_30)

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
17,18,Paul,32,Marketing,70000.0,2,33
15,16,Nina,33,HR,48000.0,7,32
3,4,Bob,35,Finance,75000.0,7,30
12,13,Karen,37,Marketing,85000.0,4,28
19,20,Rita,38,Sales,88000.0,5,27
4,5,Charlie,40,Sales,79000.0,10,25
13,14,Leo,41,Finance,90000.0,8,24
5,6,David,42,HR,85000.0,12,23
18,19,Quinn,45,Finance,80000.0,6,20
14,15,Mia,48,Sales,95000.0,5,17
6,7,Eve,50,Engineering,100000.0,15,15
7,8,Frank,60,Marketing,110000.0,18,5
8,9,Grace,65,Finance,120000.0,20,0

In [17]:
# Select only columns name, age, and annual_salary.
df_selected = df[['name', 'age', 'annual_salary']]

display(df_selected)

       name  age  annual_salary
1      Jane   25        79000.0
2     Alice   28        55000.0
3       Bob   35        75000.0
4   Charlie   40        79000.0
5     David   42        85000.0
6       Eve   50       100000.0
7     Frank   60       110000.0
8     Grace   65       120000.0
9    Hannah   30        65000.0
10      Ivy   28        67000.0
12    Karen   37        85000.0
13      Leo   41        90000.0
14      Mia   48        95000.0
15     Nina   33        48000.0
16   Olivia   29        67000.0
17     Paul   32        70000.0
18    Quinn   45        80000.0
19     Rita   38        88000.0

Task 6: Data Aggregation
Objective: Perform group-based aggregation.

Instructions:

Group the data by department and calculate the average salary for each department.

In [20]:
## Code here

# Group all employees by their department, calculate the average salary for each group in descending order.
avg_salary_df = df.groupby('department')['annual_salary'].mean().round(2).reset_index().sort_values(by='annual_salary', ascending=False)

display(avg_salary_df)

    department  annual_salary
1      Finance       91250.00
0  Engineering       82000.00
4        Sales       81750.00
3    Marketing       80000.00
2           HR       66666.67